#!/usr/bin/env python3
"""
gen_senses.py — build data/senses.json, the Czech-sense → English-answers map.

One Czech word routinely covers several English ones. Where a vocab prompt
names no sense ("cesta", not "cesta (delší)" or "silnice / cesta"), every
English word the course attaches to that sense is a correct answer, and
grading one of them wrong is the single most demoralising thing the app can
do to a student working alone.

The engine cannot work this out from the pack in front of it: `film` sits in
a1_freetime and `movie` in another pack entirely, so a per-pack rule catches
only 73 of the 182 ambiguous prompts. This precomputes the map across every
vocab pack so the engine can answer it in O(1) with one small file.

Senses are collected from ALL prompts, cued or not — "silnice / cesta" is
what makes `road` a legal answer to a bare "cesta" — but only BARE prompts
are ever widened at grading time. That rule lives in js/practice-vocab.js.

Usage: py -X utf8 codex/scripts/gen_senses.py .
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
DATA = ROOT / "data"
OUT = DATA / "senses.json"

PARENS_RE = re.compile(r"\([^)]*\)")

# Freely interchangeable English words — the same thing under two names, so
# either is right ANYWHERE, including inside a sentence. This is the narrow
# column of the 2026-08-17 sweep: 221 ambiguous triples were found, but most
# depend on context (sestra = sister OR nurse; cena = price OR prize) and must
# stay strict. Only genuine synonyms are listed here.
#
# Deliberately EXCLUDED, and why:
#   autobus  bus/coach     — a coach is a long-distance bus, not the same thing
#   město    city/town     — size distinction worth keeping
#   už       already/yet   — different meanings; the app teaches the contrast
#   hodina   hour/lesson   — different things
#   stůl     table/desk    — different objects; the Czech prompt is cued instead
#
# Extend freely — one line each, and the grader picks it up on regeneration.
SYNONYM_GROUPS = [
    ["phone", "telephone"],
    ["shop", "store"],
    ["film", "movie"],
    ["flat", "apartment"],
    ["mistake", "error"],
    ["answer", "reply", "response"],
    ["buy", "purchase"],
    ["trousers", "pants"],
    ["sweater", "jumper"],
    ["football", "soccer"],
    ["clothes", "clothing"],
    ["pharmacy", "chemist"],
    ["quick", "fast"],
    ["ill", "sick"],
    ["child", "kid"],
    ["holiday", "vacation"],
    ["lift", "elevator"],
    ["rubbish", "garbage"],
    ["biscuit", "cookie"],
    ["timetable", "schedule"],
    ["tv", "television"],
]


def senses(cz: str) -> list[str]:
    """"silnice / cesta" -> [silnice, cesta]; "cesta (delší)" -> [cesta]."""
    out = []
    for part in str(cz or "").split("/"):
        bare = re.sub(r"\s+", " ", PARENS_RE.sub(" ", part)).strip().lower()
        if bare:
            out.append(bare)
    return out


def main() -> int:
    by_sense: dict[str, set[str]] = defaultdict(set)
    packs = 0
    for f in sorted((DATA / "vocab" / "blocks").glob("*.json")):
        pack = json.loads(f.read_text(encoding="utf-8"))
        packs += 1
        for b in pack.get("blocks") or []:
            for it in b.get("items") or []:
                if not isinstance(it, dict) or it.get("gap"):
                    continue
                en = str(it.get("en") or "").strip()
                if not en:
                    continue
                for s in senses(it.get("cz")):
                    by_sense[s].add(en)

    # Only ambiguous senses are worth shipping — the rest change nothing.
    ambiguous = {s: sorted(v) for s, v in by_sense.items() if len(v) > 1}

    # word -> the group's first member, so grading can compare canonical forms
    # instead of expanding every combination.
    canon: dict[str, str] = {}
    for group in SYNONYM_GROUPS:
        lead = group[0]
        for w in group:
            canon[w] = lead

    payload = {
        "version": 2,
        "app": "rue-exp",
        "note": ("Czech sense -> every English answer the course attaches to it. "
                 "`senses` widens grading for BARE word prompts only (no "
                 "alternative, no parenthetical gloss). `synonyms` maps freely "
                 "interchangeable English words to one canonical form and applies "
                 "ANYWHERE, including inside a sentence — that is the half of the "
                 "ambiguity class a bare-prompt rule cannot reach. Generated by "
                 "codex/scripts/gen_senses.py."),
        "senses": ambiguous,
        "synonyms": canon,
    }
    OUT.write_text(json.dumps(payload, ensure_ascii=False, indent=1) + "\n",
                   encoding="utf-8")

    worst = sorted(ambiguous.items(), key=lambda kv: -len(kv[1]))[:6]
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  {packs} vocab packs · {len(by_sense)} senses · "
          f"{len(ambiguous)} ambiguous")
    for s, v in worst:
        print(f"    {s:14} -> {v}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
